<a href="https://colab.research.google.com/github/LK-Hour/Fundamental-Data-Science/blob/main/Week2_Kimhour_Loem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 1: Welcome to Python!


## Goals
Welcome to your second lab session! In this lab, you will gain hands-on experience with Python programming and learn how Python is used in Data Science.

The first goal of this lab is to ensure that your Python 3 environment is set up correctly and running without issues. If you encounter any problems, please let the tutor know.

This lab will also introduce you to writing your first Python programs, using both scripts and the interactive environment, and applying Python to work with real datasets.

In addition to basic Python concepts, you will begin using Python for basic data analysis tasks, such as loading data, exploring datasets, and performing simple operations that are common in Data Science workflows.

Even if some tasks seem simple, please complete them carefully, as they form the foundation for future labs.

As always, have fun and enjoy the rest of the class period!

## Submission

Name your Jupyter notebook `week{number}_yourname.ipynb`. For example: Group1_week2.ipybn/pdf

## Let's get started!

## Part 1: Basic Python programming

### Loop

**Exercise 1:** Print First 10 natural numbers using while loop

**Expected output:**
````
0
1
2
3
4
5
6
7
8
9
10
````

In [ ]:
i = 0
while i <= 10:
  print (i)
  i += 1

0
1
2
3
4
5
6
7
8
9
10


### String

**Exercise 2**: Given 2 strings, s1 and s2, concat 2 strings
Given:
````
s1 = "Hello"
s2 = "World"
````
**Expected Output:**
````
    Hello World

````

In [ ]:
s1 = "Hello"
s2 = "World"
print (s1 + ' ' + s2)

Hello World


**Exercise 3**: Removal all the characters other than integers from string
Given:
````
I am 25 years and 10 months old
````
**Expected Output:**
````
2510
````
**Hint:
- list comprehension,
- Join(),
- isdigit()

In [ ]:
string = 'I am 25 years and 10 months old'
numbers = [x for x in string if x.isdigit()]
print (''.join(numbers))

2510


### Tuple

**Exercise 4**: Create a tuple with single item 50

In [ ]:
tuple_50 = (50,)
print (tuple_50)

(50,)


**Exercise 4**: Unpack the following tuple into 4 variables
````
aTuple = (10, 20, 30, 40)
````

**Expected output:**

````
aTuple = (10, 20, 30, 40)
# Your code
print(a) # should print 10
print(b) # should print 20
print(c) # should print 30
print(d) # should print 40
````

In [ ]:
aTuple = (10, 20, 30, 40)
a = aTuple[0]
b = aTuple[1]
c = aTuple[2]
d = aTuple[3]

print(a)
print(b)
print(c)
print(d)

10
20
30
40


**Exercise 5**: Swap the following two tuples
````
tuple1 = (11, 22)
tuple2 = (99, 88)
````
**Expected output:**
````
tuple1 = (99, 88)
tuple2 = (11, 22)
````

In [ ]:
tuple1 = (11, 22)
tuple2 = (99, 88)
tuple1, tuple2 = tuple2, tuple1
print ('tuple1: ', end='')
print (tuple1)
print ('tuple2: ', end='')
print (tuple2)

tuple1: (99, 88)
tuple2: (11, 22)


### Set

**Exercise 6**: Add a list of elements to a given set
````
sampleSet = {"Yellow", "Orange", "Black"}
sampleList = ["Blue", "Green", "Red"]
````
**Expected output:**

In set item order is not a concern
````
{'Green', 'Yellow', 'Black', 'Orange', 'Red', 'Blue'}
````
**Hint: use update()

In [ ]:
sampleSet = {"Yellow", "Orange", "Black"}
sampleList = ["Blue", "Green", "Red"]
sampleSet.update(sampleList)
print (sampleSet)

{'Green', 'Orange', 'Blue', 'Red', 'Black', 'Yellow'}


**Exercise 7**: Returns a new set with all items from both sets by removing duplicates
````
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
````
**Expected output:**

````
{70, 40, 10, 50, 20, 60, 30}
````
Remember set is unordered so not necessary this will be the order of the item.

In [ ]:
set1 = {10, 20, 30, 40, 50}
set2 = {30, 40, 50, 60, 70}
set3 = set1.union(set2)
print (set3)

{70, 40, 10, 50, 20, 60, 30}


### Dictionaries

**Exercise 8**: Below are the two lists convert it into the dictionary
````
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
````
**Expected output:**

````
{'Ten': 10, 'Twenty': 20, 'Thirty': 30}


In [ ]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
dictionary = dict(zip(keys, values))
print (dictionary)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}


**Exercise 9**: Merge following two Python dictionaries into one
````
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
````
**Expected output:**

````
{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
````

In [ ]:
dict1 = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
dict2 = {'Thirty': 30, 'Fourty': 40, 'Fifty': 50}
dict3 = {**dict1, **dict2}
print (dict3)

{'Ten': 10, 'Twenty': 20, 'Thirty': 30, 'Fourty': 40, 'Fifty': 50}


## Mixed parts

**Exercise 10:** Write a loop to find the factorial of any number
The factorial (symbol: !) means to multiply all whole numbers from our chosen number down to 1.

**For example:** calculate the factorial of 5

5! = 5 × 4 × 3 × 2 × 1 = 120

**Expected output:**
````
120
````

In [ ]:
def factorial(n):
  if n == 1:
    return 1
  return n*factorial(n-1)
print(factorial(5))

120


**Exercise 11:** Reverse a given integer number
Given:
````
76542
````

**Expected output:**
````
24567
````

In [ ]:
num = 76542
reversed_num = 0
for i in range(len(str(num))):
  a = num % 10
  num = num // 10
  reversed_num = reversed_num * 10 + a
print (reversed_num)

24567


**Exercise 12:** Find the sum of the series 2 +22 + 222 + 2222 + .. n terms

Given:
````
number_of_terms = 5
````
So series will become 2 + 22 + 222 + 2222 + 22222

**Expected output:**
````
24690
````

In [ ]:
number_of_terms = 5
total = 0
for i in range(number_of_terms):
  result = 2
  for j in range(i):
    result = result * 10 + 2
  total += result
print (total)

24690


**Exercise 13:** Create a function that can accept two arguments name and age and print its value

In [ ]:
def greet (name, age):
  print("Hello " + name + " you are " + str(age) + " Years old.")
greet (name= "Kimhour", age = 20)

Hello Kimhour you are 20 Years old.


**Exercise 14:** Write a function func1() such that it can accept a variable length of  argument and print all arguments value
````
func1(20, 40, 60)
func1(80, 100)
````

**Expected Output:**

After func1(20, 40, 60):
````
20
40
60
````

After func1(80, 100):
````
80
100
````

In [ ]:
def func1 (*nums):
  for i in nums:
    print (i)
print('Func1 (20, 40, 60): ')
func1(20, 40, 60)
print('Func1 (80, 100): ')
func1(80, 100)


Func1 (20, 40, 60): 
20
40
60
Func1 (80, 100): 
80
100


**Exercise 15:** Create a function showEmployee() in such a way that it should accept employee name, and it’s salary and display both, and if the salary is missing in function call it should show it as 9000

**Expected Output:**
````
showEmployee("Ben", 9000)
showEmployee("Ben")
````

Should Produce:
````
Employee Ben salary is: 9000
Employee Ben salary is: 9000
````

In [ ]:
def showEmployee(name, salary = 9000):
  print("Employee " + name + " salary is: " + str(salary))
showEmployee("Ben", 9000)

Employee Ben salary is: 9000


In [ ]:
showEmployee("Ben")

Employee Ben salary is: 9000


**Exercise 16:** Given a two integer numbers return their product and  if the product is greater than 1000, then return their sum

Given:

````
number1 = 20
number2 = 30
````

Expected Output:

`````
The result is 600
````
Given:
````
number1 = 40
number2 = 30
````
Expected Output:
````
The result is 70
````

In [ ]:
def isGreaterThan1000(num1, num2):
  product = num1 * num2
  if product > 1000:
    print("The result is " + str(num1 + num2))
  else:
    print("The result is " + str(product))

In [ ]:
number1 = 20
number2 = 30
isGreaterThan1000(number1, number2)


The result is 600


In [ ]:
number1 = 40
number2 = 30
isGreaterThan1000(number1, number2)

The result is 70


**Exercise 17**: Given a two list of equal size create a set such that it shows the element from both lists in the pair

**Expected Output:**
````
First List  [2, 3, 4, 5, 6, 7, 8]
Second List  [4, 9, 16, 25, 36, 49, 64]
Result is  {(6, 36), (8, 64), (4, 16), (5, 25), (3, 9), (7, 49), (2, 4)}
````
**Hint: use zip()

In [ ]:
list1 = [2, 3, 4, 5, 6, 7, 8]
list2 = [4, 9, 16, 25, 36, 49, 64]
set_merge = {(x, y) for x, y in zip(list1, list2)}
print(set_merge)

{(7, 49), (2, 4), (4, 16), (8, 64), (6, 36), (3, 9), (5, 25)}


**Exercise 18:** Given a range of first 10 numbers, Iterate from start number to the end number and print the sum of the current number and previous number

Reference article for help:
- [Python range() function](https://pynative.com/python-range-function/)
- [Calculate sum and average in Python](https://pynative.com/python-program-to-calculate-sum-and-average-of-numbers/)

**Expected Output:**
````
Printing current and previous number sum in a given range(10)
Current Number 0 Previous Number  0  Sum:  0
Current Number 1 Previous Number  0  Sum:  1
Current Number 2 Previous Number  1  Sum:  3
Current Number 3 Previous Number  2  Sum:  5
Current Number 4 Previous Number  3  Sum:  7
Current Number 5 Previous Number  4  Sum:  9
Current Number 6 Previous Number  5  Sum:  11
Current Number 7 Previous Number  6  Sum:  13
Current Number 8 Previous Number  7  Sum:  15
Current Number 9 Previous Number  8  Sum:  17
````

In [ ]:
result = 0
print('Printing current and previous number sum in a given range(10)')
for i in range (10):
  if (i == 0):
    result = 0
    print("Current Number " + str(i) + " Previous Number " + str(i) + " Sum: " + str(result))
  else:
    result = i + (i-1)
    print("Current Number " + str(i) + " Previous Number " + str(i-1) + " Sum: " + str(result))
  i += i



Printing current and previous number sum in a given range(10)
Current Number 0 Previous Number 0 Sum: 0
Current Number 1 Previous Number 0 Sum: 1
Current Number 2 Previous Number 1 Sum: 3
Current Number 3 Previous Number 2 Sum: 5
Current Number 4 Previous Number 3 Sum: 7
Current Number 5 Previous Number 4 Sum: 9
Current Number 6 Previous Number 5 Sum: 11
Current Number 7 Previous Number 6 Sum: 13
Current Number 8 Previous Number 7 Sum: 15
Current Number 9 Previous Number 8 Sum: 17


**Exercise 19**: Delete set of keys from Python Dictionary
Given:
````
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
  
}
keysToRemove = ["name", "salary"]
````
**Expected output:**

````
{'city': 'New york', 'age': 25}
````

In [ ]:
from random import sample
sampleDict = {
  "name": "Kelly",
  "age":25,
  "salary": 8000,
  "city": "New york"
}
sampleDict.pop('name')
sampleDict.pop('salary')
print(sampleDict)

{'age': 25, 'city': 'New york'}


**Exercise 20:** Given a string, display only those characters which are present at an even index number.
For example str = "pynative" so you should display ‘p’, ‘n’, ‘t’, ‘v’.

Reference article for help: Python Input and Output

**Expected Output:**
````
Orginal String is  pynative
Printing only even index chars
p
n
t
v
````

In [ ]:
string = 'pynative'
for i in range(len(string)):
  if i % 2 == 0:
    print(string[i])

p
n
t
v


**Exercise 21:** Given a list of numbers, return True if first and last number of a list is same

**Expected Output:**
````
Given list is  [10, 20, 30, 40, 10]
result is True
Given list is  [10, 20, 30, 40, 50]
result is False
````

In [ ]:
def isFirstAndLastSame(list1):
  if list1[0] == list1[-1]:
    print('result is True')
  else :
    print('result is False')
list1 = [10, 20, 30, 40, 10]
isFirstAndLastSame(list1)
list2 = [10, 20, 30, 40, 50]
isFirstAndLastSame(list2)

result is True
result is False


**Exercise 22:** Given a list of numbers, Iterate it and print only those numbers which are divisible of 5

**Expected Output:**
````
Given list is  [10, 20, 33, 46, 55]
Divisible of 5 in a list
10
20
55
````


In [ ]:
list5 = [10, 20, 33, 46, 55]
for i in list5:
  if i % 5 == 0:
    print(i)

10
20
55


**Exercise 23:** Return the total count of sub-string “Emma” appears in the given string

Given string is “Emma is good developer. Emma is a writer”

**Expected Output:**
````
Emma appeared 2 times
````

In [ ]:
string1 = 'Emma is good developer. Emma is a writer'
print('Emma appeared', string1.count('Emma'), 'times')

Emma appeared 2 times


**Exercise 24:** Print the following pattern
````
1
2 2
3 3 3
4 4 4 4
5 5 5 5 5
````

In [ ]:
for i in range(1, 6):
  for j in range(i):
    print(i, end=' ')
  print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


**Exercise 25:** Print downward Half-Pyramid Pattern with Star (asterisk)

````
* * * * *  
* * * *  
* * *  
* *  
*
````

In [ ]:
for i in range(5, 0, -1):
  for j in range(i):
    print('*', end=' ')
  print()

* * * * * 
* * * * 
* * * 
* * 
* 


**Exercise 26:** Write a function called exponent(base, exp) that returns an int value of base raises to the power of exp.
Note here exp is a non-negative integer, and the base is an integer.

**Expected Output:**

Case 1:

base = 2
exponent = 5

2 raises to the power of 5 is: 32 i.e. (2 *2 * 2 *2 *2 = 32)

Case 2:

base = 5
exponent = 4

5 raises to the power of 4 is: 625 i.e. (5 *5 * 5 *5 = 625)

In [ ]:
def exponent(base, exp):
  if exp == 0:
    return 1
  elif exp == 1:
    return base
  elif exp > 1:
    return base ** exp

In [ ]:
print(exponent(2, 5))

32


In [ ]:
print(exponent(5, 4))

625


## Part 2: Python for Data science

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Cloud Computing/Heart_Disease_Prediction.csv")
df.head()


Age  Sex  Chest pain type   BP  Cholesterol  FBS over 120  EKG results  \
0   70    1                4  130          322             0            2   
1   67    0                3  115          564             0            2   
2   57    1                2  124          261             0            0   
3   64    1                4  128          263             0            0   
4   74    0                2  120          269             0            2   

   Max HR  Exercise angina  ST depression  Slope of ST  \
0     109                0            2.4            2   
1     160                0            1.6            2   
2     141                0            0.3            1   
3     105                1            0.2            2   
4     121                1            0.2            1   

   Number of vessels fluro  Thallium Heart Disease  
0                        3         3      Presence  
1                        0         7       Absence  
2                        0         7      Presence  
3                        1         7       Absence  
4                        1         3       Absence

**Discussion 1**:
````
1. Why do we load data instead of typing it manually?
2. What does each row represent?
3. What does each column represent?
4. Why do we look at the first few rows?
````

**Answer**:
````
1. We laod data instead of typing it manually because the  loading data is fundamental for handling large, complex datasets efficiently, accurately, and in a reproducible manner, which are all cornerstones of effective data science.
2. Each row represent the record of a person.
3. Each column represent the category of the each record for example Age, Sex .etc.
4. We are looking at the first few row because it is a primarily used for quickly inspecting the structure, column names, and sample data of a dataset, by using the df.head() function.
````

In [ ]:
df.shape
df.columns

Index(['Age', 'Sex', 'Chest pain type', 'BP', 'Cholesterol', 'FBS over 120',
       'EKG results', 'Max HR', 'Exercise angina', 'ST depression',
       'Slope of ST', 'Number of vessels fluro', 'Thallium', 'Heart Disease'],
      dtype='object')

In [ ]:
len(df)

270

**Discussion 2**:
````
1.What does one row represent in this dataset?
2. What does one column represent?
3. Why is it important to know the number of rows and columns before analysis?
4. How many observations are in the dataset?
5. Which columns are numeric? Which are categorical?
````

**Answer**:
````
1. This one row represent all the column in the dataset.
2. One column represent the categry of the record.
3. Because that let us know how big the dataset we are working with.
4. There are 270 observation(instance) in this dataset.
5. All of the column are numeric except the "Heart Disease" column shown as categorical.
````

In [ ]:
df.dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Age                      270 non-null    int64  
 1   Sex                      270 non-null    int64  
 2   Chest pain type          270 non-null    int64  
 3   BP                       270 non-null    int64  
 4   Cholesterol              270 non-null    int64  
 5   FBS over 120             270 non-null    int64  
 6   EKG results              270 non-null    int64  
 7   Max HR                   270 non-null    int64  
 8   Exercise angina          270 non-null    int64  
 9   ST depression            270 non-null    float64
 10  Slope of ST              270 non-null    int64  
 11  Number of vessels fluro  270 non-null    int64  
 12  Thallium                 270 non-null    int64  
 13  Heart Disease            270 non-null    object 
dtypes: float64(1), int64(12), 

**Discussion 3**:
````
1. Why is knowing data types important in data analysis?
2. What problems can happen if data types are incorrect?
3. Are there any missing values?
4. Which columns might need cleaning?
````

**Answer**:
````
1. - Identifies whether data is numerical or categorical
- Ensures correct statistical calculations
- Helps machine learning models interpret features properly
- Prevents analytical errors.
Example:
- Age and cholesterol → numerical
- Sex and chest pain type → categorical

2. - Incorrect statistical results
- Model confusion (classification vs regression)
- Calculation errors
- Misleading predictions
Example:
- If age is treated as text, we cannot compute average age

3. In the Heart Disease dataset, there are no missing values.
To verify this:
- We checked whether any column contains null or empty values
- All columns show 0 missing values

4. - Categorical variables stored as numbers (Sex, Chest pain..)
- Possible outliers (very high cholesterol or blood pressure)
- Heart Disease
- Converting to binary (0 and 1)
Data cleaning improves:
- Accuracy
- Model performance
- Reliability of prediction

````

In [ ]:
df.isnull().sum()

Age                        0
Sex                        0
Chest pain type            0
BP                         0
Cholesterol                0
FBS over 120               0
EKG results                0
Max HR                     0
Exercise angina            0
ST depression              0
Slope of ST                0
Number of vessels fluro    0
Thallium                   0
Heart Disease              0
dtype: int64

In [ ]:
df.describe()

Age         Sex  Chest pain type          BP  Cholesterol  \
count  270.000000  270.000000       270.000000  270.000000   270.000000   
mean    54.433333    0.677778         3.174074  131.344444   249.659259   
std      9.109067    0.468195         0.950090   17.861608    51.686237   
min     29.000000    0.000000         1.000000   94.000000   126.000000   
25%     48.000000    0.000000         3.000000  120.000000   213.000000   
50%     55.000000    1.000000         3.000000  130.000000   245.000000   
75%     61.000000    1.000000         4.000000  140.000000   280.000000   
max     77.000000    1.000000         4.000000  200.000000   564.000000   

       FBS over 120  EKG results      Max HR  Exercise angina  ST depression  \
count    270.000000   270.000000  270.000000       270.000000      270.00000   
mean       0.148148     1.022222  149.677778         0.329630        1.05000   
std        0.355906     0.997891   23.165717         0.470952        1.14521   
min        0.000000     0.000000   71.000000         0.000000        0.00000   
25%        0.000000     0.000000  133.000000         0.000000        0.00000   
50%        0.000000     2.000000  153.500000         0.000000        0.80000   
75%        0.000000     2.000000  166.000000         1.000000        1.60000   
max        1.000000     2.000000  202.000000         1.000000        6.20000   

       Slope of ST  Number of vessels fluro    Thallium  
count   270.000000               270.000000  270.000000  
mean      1.585185                 0.670370    4.696296  
std       0.614390                 0.943896    1.940659  
min       1.000000                 0.000000    3.000000  
25%       1.000000                 0.000000    3.000000  
50%       2.000000                 0.000000    3.000000  
75%       2.000000                 1.000000    7.000000  
max       3.000000                 3.000000    7.000000

**Discussion 4**:
````
1. What does average (mean) tell us about data?
2. Why might min and max be misleading sometimes?
3. Which variable has the highest average?
4. Are there any unusual values?
````

**Answer**:
````
1. Mean tells the “typical” value of a column (average level).
2. Min/max can be misleading because outliers can stretch them.
3. Highest average variable (numeric) = Cholesterol (mean = 249.66)
4. Unusual values (possible outliers):
  - Cholesterol max 564 (very high)
  - BP max 200 (high)
  - ST depression max 6.2 (high)
````

In [ ]:
df_filtered = df[df["Age"] > 0]
df_filtered.shape

(270, 14)

**Discussion 5**:
````
1. Why might we want to remove some rows from a dataset?
2. What is the difference between cleaning data and losing data?
3. How many rows were removed?
````

**Answer**:
````
1. Remove rows with invalid, duplicate, or incorrect data.
2. Cleaning data fixes errors; losing data removes rows without reason and may cause bias.
3. No rows removed  minimum age is 29, so all 270 rows remain.
````